services:
  make:
    image: ethan605/zmk-corne:latest
    container_name: zmk-corne-make
    build: .
    volumes:
      # Config files: keymap, shields, .conf
      - ./config:/zmk-config:ro

      # Build output: .uf2 files
      - ./firmware:/firmware:rw
