manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ethan605
      url-base: https://github.com/ethan605
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: edf5c0814fd3ea202e43aad2d68fd32e882a518c   # v0.3.0
      import: app/west.yml       # Pulls in Zephyr and all ZMK dependencies
    - name: zmk-dongle-screen
      remote: ethan605
      revision: 3a8709f84cfceff6335a77b88e3d829394588ae9   # Dongle screen redesign: connections one-liner, 2x2 modifiers, enlarged roller, Snazzy palette
  self:
    path: config
